---
- name: Install Helm v3
  shell: curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Verify Helm Installation
  command: helm version --short
  register: helm_version
  changed_when: false

- name: Display Helm Version
  debug:
    msg: "{{ helm_version.stdout }}"
