---
plugin_manager_version: "2.13.0"
jenkins_plugins:
  - workflow-aggregator
  - git
  - github-branch-source
  - docker-workflow
  - sonar
  - maven-plugin
  - eclipse-temurin-installer
  - credentials-binding
  - dependency-check-jenkins-plugin
  - aws-credentials
  - pipeline-utility-steps
