# Global variables for all Ansible hosts
---
ansible_user: ec2-user
ansible_ssh_private_key_file: ../terraform/environments/dev/spms-dev.pem
ansible_python_interpreter: /usr/bin/python3

# Common security settings
security_hardening:
  selinux_enabled: true
  firewall_enabled: true
  auditd_enabled: true

# Common packages
common_packages:
  - docker
  - java-11-openjdk
  - git
  - wget
  - unzip
  - jq
  - curl
  - vim
  - python3
