---
# Common variables for all environments
ansible_python_interpreter: /usr/bin/python3

# Java configuration
java_version: "21"
java_distribution: "corretto"

# Maven configuration
maven_version: "3.9.6"

# kubectl configuration
kubectl_version: "1.29.0"

# Docker configuration
docker_users:
  - "{{ ansible_user }}"
