---
# ───────────────────────────────────────────────────────────────────
# Playbook: SonarQube Stack
# ───────────────────────────────────────────────────────────────────
- name: Deploy SonarQube Stack
  hosts: sonarqube
  gather_facts: false

  roles:
    - sonarqube
