apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::365269738775:role/petclinic-dev-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::365269738775:role/Petclinic-dev-ec2-role
      groups:
      - system:masters
      username: ec2-admin
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
