apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec2-user-namespace-manager
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ec2-user-namespace-manager-binding
subjects:
  - kind: Group
    name: ec2-user-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ec2-user-namespace-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ec2-user-petclinic-admin
  namespace: petclinic
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ec2-user-petclinic-admin-binding
  namespace: petclinic
subjects:
  - kind: Group
    name: ec2-user-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ec2-user-petclinic-admin
  apiGroup: rbac.authorization.k8s.io
