{{- range $serviceKey, $serviceValue := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceValue.name }}
  labels:
    app: {{ $serviceValue.name }}
    project: spring-petclinic
spec:
  replicas: {{ $serviceValue.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ $serviceValue.name }}
  template:
    metadata:
      labels:
        app: {{ $serviceValue.name }}
    spec:
      containers:
        - name: {{ $serviceValue.name }}
          image: "{{ $.Values.global.imageRegistry }}/{{ $serviceValue.imageName }}:{{ $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $serviceValue.port }}
          env:
            {{- range $.Values.commonEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- if $serviceValue.extraEnv }}
            {{- range $serviceValue.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- if $serviceValue.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ $serviceValue.livenessProbe.path }}
              port: {{ $serviceValue.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          {{- end }}
          {{- if $serviceValue.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ $serviceValue.readinessProbe.path }}
              port: {{ $serviceValue.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          {{- end }}
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
{{- end }}
